### ISSUE TITLE
Parameter validation is not applied to proposalnew action

### ISSUE THREAD

**Issue by tommccann777** [FreeosDAO/Dividend.temp#1]
I ran the following command at 11:15 on 18/3/2021:
proton push action freeosdivide proposalnew '["freeosfreeos", "alanappleton", 4, -15.0, "20000.0000 XPR", 20, false]' -p freeosfreeos

The command ran successfully and created a proposal:
![image](https://user-images.githubusercontent.com/18106735/111610358-25e54900-8840-11eb-9728-5eead121b19a.png)

Parameter validation is required on:
roi_target_cap (set to 4)
period_percentage (set to -15.0)
threshold (set to 20000.0000 XPR)

**Comment by andyzal** [comment]
Corrections in progress. Thanks.

**Comment by andyzal** [comment]
Actually, (ver. 125) only threshold token symbol is not verified.

**Comment by Jkelsey-freedao** [comment]
still happens.

![image](https://user-images.githubusercontent.com/68309081/114017640-5f99f480-98c0-11eb-8e5d-08d1f880bd3a.png)
