### ISSUE TITLE
Dividcompute was payout out to locked NFT.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/Dividend.temp#10]
1. Set up a new NFT for jamiejackson in iteration 47 with roi=1, rates_left=5 and Locked=True (1).
2. Checked freeos333333 deposits table, there were accrued freeos for iterations 44, 45 and 46.
3. Ran dividcompute in iteration 47 successfully.
4. Checked transactions in freeos333333 account and jamiejackson was paid out in iterations 44, 45 and 46.
5. Checked NFT for jamiejackson and rates_left had counted down to 2. 
6. Dividcompute was paying out to jamiejackson even though the NFT was locked. Was not expecting any payout to jamiejackson as the NFT was locked.
![image](https://user-images.githubusercontent.com/77765830/114962980-e0a84b80-9ebf-11eb-883f-e13795c2d270.png)
![image](https://user-images.githubusercontent.com/77765830/114962904-b6ef2480-9ebf-11eb-83e6-4e7649c65ff0.png)
![image](https://user-images.githubusercontent.com/77765830/114962925-bfdff600-9ebf-11eb-92a8-f4c3af90748b.png)
![image](https://user-images.githubusercontent.com/77765830/114962941-c9695e00-9ebf-11eb-9910-96b8fb2a9e16.png)

**Comment by andyzal** [comment]
Note: jamiejackson has HORIZONTAL CAP (2). The parameter locked is ignored as apply only to the VERTICAL CAP (3)
Not an error.

**Comment by judytan21** [comment]
19/4/21  jamiejackson was set up with roi-target-cap of 1 and as per Andrew's explanation, the locked parameter only applies for founders with roi-target-cap of 3. The system will still allow locked to be selected for roi 1 & 2 but will ignore it. Discussed with Andrew as to why there are no validations in place to only require mandatory fields for the roi-target-cap to be entered and was told that the validation will be in place for the dividend frontend but not in bloks.io.
