### ISSUE TITLE
Unable to create a new proposal

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/Dividend.temp#17]
QA2 env. Bloks.io. Login as freeosfreeos
Proposer name in new proposal is freeosfreeos as in Whitelist. 
Entered remaining info required for new proposal.
On submitting transaction, assertion failure: Proposer name not authorised by whitelist.
See screenshot below:
![image](https://user-images.githubusercontent.com/77765830/116498507-00973080-a8fe-11eb-81f1-fff6c70ea073.png)
![image](https://user-images.githubusercontent.com/77765830/116498574-27556700-a8fe-11eb-98e2-4aaa9f123496.png)

**Comment by andyzal** [comment]
Authorization has been corrected. Actually the version of software with this correction is 133.
