### ISSUE TITLE
A new proposal can be created which replaces the previous (unexpired) proposal

### ISSUE THREAD

**Issue by tommccann777** [FreeosDAO/Dividend.temp#2]
This may not be a problem in production but I was able to create a new proposal which replaced an existing proposal that was still 'active' i.e. not expired.

It may be better to warn the user that a proposal is still active and has not been voted on yet. Perhaps best to check with JK to see if this is an issue or not.

**Comment by andyzal** [comment]
The issue is corrected before current version 125. Actually proposer may only remove completely the active proposal. The issue is closed but left here for arch reasons.
