### ISSUE TITLE
Second vote on proposal failed

### ISSUE THREAD

**Issue by tommccann777** [FreeosDAO/Dividend.temp#3]
Test conducted at 11.50pm on 18/3/2021:

I created a new proposal.

First, freeandyandy voted with 2 = yes
proton push action freeosdivide proposalvote '["freeandyandy", 2]' -p freeandyandy

Second, freeosandy11 voted, also with 2 = yes
proton push action freeosdivide proposalvote '["freeosandy11", 2]' -p freeosandy11

The result was as follows:
![image](https://user-images.githubusercontent.com/18106735/111615171-4bc11c80-8845-11eb-9cb8-42b68ca1163a.png)

**Comment by andyzal** [comment]
This issue was solved. Thanks for Tom and Jerome.
