### ISSUE TITLE
Proposal cannot be created even after propreset

### ISSUE THREAD

**Issue by Jkelsey-freedao** [FreeosDAO/Dividend.temp#7]
Called propreset as freeosfreeos and succeeded.
proprows showed the following:

![image](https://user-images.githubusercontent.com/68309081/113559646-ded7c000-9655-11eb-979b-23c87e5a78aa.png)

Proposed an NFT using:

`cleos --url https://api-testnet-proton.eosarabia.net:443 push action freeosdivide proposalnew '{"proposer":"freeosfreeos","eosaccount":"frankyfellon","roi_target_cap":1,"period_percentage":"3","threshold":"0.0000 FREEOS","rates_left":20,"locked":false}' -p freeosfreeos@active`

Received this error:

assertion failure with message: There exists not expired proposal! Consider removing it.
```

{
  "code": 500,
  "message": "Internal Service Error",
  "error": {
    "code": 3050003,
    "name": "eosio_assert_message_exception",
    "what": "eosio_assert_message assertion failure",
    "details": [
      {
        "message": "assertion failure with message: There exists not expired proposal! Consider removing it.",
        "file": "wasm_interface.cpp",
        "line_number": 1075,
        "method": "eosio_assert"
      },
      {
        "message": "pending console output: ",
        "file": "apply_context.cpp",
        "line_number": 113,
        "method": "exec_one"
      }
    ]
  }

```

**Comment by andyzal** [comment]
Seems to be corrected in current version 125 (deployed). It was proposal expiration  issue after adding the preventing of re-editing active proposal.
